name: GoldEconomy
version: ${project.version}
api-version: 1.13
authors: [Hempfest, Illuminatiiiiii, ms5984]
load: STARTUP
depend:
  - HempCore
soft-depend:
  - Vault
description: ${project.description}
main: com.youtube.hempfest.goldeco.GoldEconomy