name: GoldEconomy
version: 1.1.0
api-version: 1.13
authors: [Hempfest, Illuminatiiiiii]
depend:
  - HempCore
soft-depend:
  - Vault
description: A customizable economy plugin
main: com.youtube.hempfest.goldeco.GoldEconomy